"""
Research pipeline structured output models.

All agent outputs are validated via Pydantic for type safety
and downstream consumption.
"""

from datetime import datetime
from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class Source(BaseModel):
    """A cited source with credibility metadata."""
    url: str = ""
    title: str = ""
    credibility_score: float = Field(0.5, ge=0.0, le=1.0)
    access_date: Optional[datetime] = None


class ResearchFinding(BaseModel):
    """A single validated claim with evidence."""
    claim: str
    evidence: str
    confidence: float = Field(0.5, ge=0.0, le=1.0)
    sources: List[Source] = Field(default_factory=list)
    contradictions: List[str] = Field(default_factory=list)


class ReportSection(BaseModel):
    """A structured report section."""
    id: str
    title: str
    description: str
    word_count_target: int = 500
    findings: List[ResearchFinding] = Field(default_factory=list)


class SubTask(BaseModel):
    """A decomposed research sub-task."""
    id: str
    query: str
    agent_type: Literal[
        "market_researcher",
        "financial_analyst",
        "risk_assessor",
        "compliance_checker",
        "data_analyst",
        "writer",
        "general",
    ] = "general"
    verification_fn_description: str = ""
    max_steps: int = Field(5, ge=1, le=20)
    estimated_effort: Literal["high", "medium", "low"] = "medium"
    suggested_skills: List[str] = Field(
        default_factory=list,
        description="Specialist skills the planner recommends for this sub-task",
    )


class ResearchPlan(BaseModel):
    """A complete research plan generated by the Planner."""
    summary: str
    sub_tasks: List[SubTask] = Field(default_factory=list)
    key_dimensions: List[str] = Field(default_factory=list)
    clarification_questions: List[dict] = Field(default_factory=list)
    estimated_duration_minutes: int = 10


class CitationGraph(BaseModel):
    """Graph of source-to-claim relationships."""
    nodes: List[dict] = Field(default_factory=list)
    edges: List[dict] = Field(default_factory=list)


class ResearchReport(BaseModel):
    """Final structured research report."""
    title: str
    summary: str
    sections: List[ReportSection] = Field(default_factory=list)
    findings: List[ResearchFinding] = Field(default_factory=list)
    source_graph: CitationGraph = Field(default_factory=CitationGraph)
    confidence_distribution: dict = Field(default_factory=dict)


class AnalysisResult(BaseModel):
    """Data Analyst Agent output."""
    code: str
    result_summary: str
    insight: str
    charts: List[dict] = Field(default_factory=list)
    # Python-rendered figures as base64 PNG — populated by upgraded DataAnalystAgent
    figures: List[dict] = Field(
        default_factory=list,
        description=(
            "List of rendered figures, each: "
            "{'format': 'png', 'base64': '<b64>', 'size_kb': N}"
        ),
    )
    execution_time_ms: int = 0


class VerificationCheck(BaseModel):
    """A single verification criterion result."""
    criterion: str
    passed: bool
    detail: str
    sources_count: int = 0


class VerificationResult(BaseModel):
    """Result of verifying a sub-task or finding."""
    sub_task_id: str = ""
    passed: bool
    overall_confidence: float = Field(0.5, ge=0.0, le=1.0)
    checks: List[VerificationCheck] = Field(default_factory=list)


class ProgressMessage(BaseModel):
    """Structured progress event for WebSocket."""
    stage: Literal[
        "planning", "clarifying", "researching", "writing",
        "reviewing", "completed", "error",
    ]
    progress_pct: int = Field(0, ge=0, le=100)
    current_task: str = ""
    sub_task_id: Optional[str] = None
    detail: Optional[dict] = None


class SubStageProgress(BaseModel):
    """Progress of an individual sub-stage."""
    id: str
    label: str
    status: Literal["pending", "running", "completed", "failed"]
    progress_pct: int = 0
