"""datasource_registry.py — static registry of all official knowledge sources.

Contains the full list of 60+ sources covering finance, academia, government,
corporate, news, industry, environment, law, international and health domains.
"""
from __future__ import annotations

import json
import logging
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

logger = logging.getLogger(__name__)

# ── Master source list ──────────────────────────────────────────────────────

OFFICIAL_SOURCES: list[dict] = [

    # ── 金融数据 ──────────────────────────────────────────────────────────

    {
        "key": "fin_stock_cn",
        "name": "中国A股行情数据",
        "description": "沪深A股实时行情、历史K线、涨跌停、换手率、市值等完整股票行情数据。",
        "category": "金融数据",
        "domain_tags": ["A股", "股票", "上交所", "深交所", "K线", "行情"],
        "source_type": "api",
        "icon_color": "#ef4444",
        "icon_bg": "#fef2f2",
        "sample_queries": ["查询贵州茅台最新股价", "获取沪深300指数历史行情", "A股今日涨跌停统计"],
        "coverage": "1990-至今",
        "doc_count": 5200,
    },
    {
        "key": "fin_stock_hk",
        "name": "港股行情数据",
        "description": "香港联合交易所上市股票实时报价、历史K线、财务摘要及恒生指数成分股数据。",
        "category": "金融数据",
        "domain_tags": ["港股", "香港联交所", "恒生指数", "H股"],
        "source_type": "api",
        "icon_color": "#ef4444",
        "icon_bg": "#fef2f2",
        "sample_queries": ["查询腾讯控股港股收盘价", "恒生科技指数成分股", "港股今日成交额前十"],
        "coverage": "2000-至今",
        "doc_count": 2600,
    },
    {
        "key": "fin_stock_us",
        "name": "美股行情数据",
        "description": "纽交所、纳斯达克上市公司股票实时报价、财报季EPS、标普500/道琼斯指数。",
        "category": "金融数据",
        "domain_tags": ["美股", "纳斯达克", "纽交所", "标普500", "道琼斯"],
        "source_type": "api",
        "icon_color": "#ef4444",
        "icon_bg": "#fef2f2",
        "sample_queries": ["查询苹果公司最新股价", "标普500指数年度涨幅", "纳斯达克科技股市值排名"],
        "coverage": "2000-至今",
        "doc_count": 8000,
    },
    {
        "key": "fin_futures",
        "name": "期货与大宗商品数据",
        "description": "原油、黄金、铜、大豆、铁矿石、螺纹钢等大宗商品期货实时价格与历史走势。",
        "category": "金融数据",
        "domain_tags": ["期货", "大宗商品", "原油", "黄金", "铜", "大豆"],
        "source_type": "api",
        "icon_color": "#f59e0b",
        "icon_bg": "#fffbeb",
        "sample_queries": ["布伦特原油最新期货价", "COMEX黄金期货近三月行情", "大连商品交易所大豆主力合约"],
        "coverage": "2010-至今",
        "doc_count": 3400,
    },
    {
        "key": "fin_bond",
        "name": "债券市场数据",
        "description": "中国国债、地方债、企业债收益率曲线，10年期国债实时收益率，债券发行情况。",
        "category": "金融数据",
        "domain_tags": ["债券", "国债", "收益率", "企业债", "利率"],
        "source_type": "api",
        "icon_color": "#6366f1",
        "icon_bg": "#eef2ff",
        "sample_queries": ["10年期国债收益率最新值", "企业债发行规模季度统计", "债券收益率曲线数据"],
        "coverage": "2010-至今",
        "doc_count": 1800,
    },
    {
        "key": "fin_fund",
        "name": "公募基金净值数据",
        "description": "国内公募基金日净值、累计净值、基金规模、持仓披露及基金经理信息。",
        "category": "金融数据",
        "domain_tags": ["公募基金", "净值", "基金规模", "持仓"],
        "source_type": "api",
        "icon_color": "#6366f1",
        "icon_bg": "#eef2ff",
        "sample_queries": ["易方达蓝筹精选最新净值", "主动权益基金近一年收益排名", "偏股型基金规模变化"],
        "coverage": "2010-至今",
        "doc_count": 4200,
    },
    {
        "key": "fin_forex",
        "name": "外汇汇率数据",
        "description": "中国人民银行人民币汇率中间价，美元/人民币、欧元/人民币等主要货币对实时及历史数据。",
        "category": "金融数据",
        "domain_tags": ["外汇", "汇率", "人民币", "美元", "欧元", "中间价"],
        "source_type": "api",
        "icon_color": "#10b981",
        "icon_bg": "#ecfdf5",
        "sample_queries": ["人民币兑美元今日中间价", "过去一年人民币汇率走势", "欧元兑人民币历史数据"],
        "coverage": "2015-至今",
        "doc_count": 2000,
    },
    {
        "key": "fin_annual_report",
        "name": "上市公司年度报告",
        "description": "A股全部上市公司历年年度报告全文，含财务报表、股东信息、业务概述、管理层讨论。",
        "category": "金融数据",
        "domain_tags": ["年报", "财报", "上市公司", "财务报表", "A股"],
        "source_type": "web",
        "icon_color": "#8b5cf6",
        "icon_bg": "#f5f3ff",
        "sample_queries": ["宁德时代2023年年报净利润", "比亚迪历年营收增长", "白酒行业上市公司毛利率对比"],
        "coverage": "2010-至今",
        "doc_count": 120000,
    },
    {
        "key": "fin_macro_cn",
        "name": "中国宏观经济指标",
        "description": "国家统计局CPI、PPI、PMI、GDP增速、工业增加值、社会消费品零售总额等核心宏观数据。",
        "category": "金融数据",
        "domain_tags": ["CPI", "PPI", "PMI", "GDP", "宏观经济", "通胀"],
        "source_type": "api",
        "icon_color": "#10b981",
        "icon_bg": "#ecfdf5",
        "sample_queries": ["最新CPI同比增速", "制造业PMI历史数据", "GDP季度增速对比"],
        "coverage": "2010-至今",
        "doc_count": 5000,
    },

    # ── 学术研究 ──────────────────────────────────────────────────────────

    {
        "key": "acad_arxiv",
        "name": "ArXiv预印本数据库",
        "description": "物理、数学、计算机科学、经济学、统计学等领域的学术预印本，每日更新最新论文。",
        "category": "学术研究",
        "domain_tags": ["论文", "学术", "预印本", "AI", "数学", "物理", "经济学"],
        "source_type": "api",
        "icon_color": "#b45309",
        "icon_bg": "#fef3c7",
        "sample_queries": ["大型语言模型最新论文", "量子计算arxiv研究进展", "强化学习近期预印本"],
        "coverage": "1991-至今",
        "doc_count": 2400000,
    },
    {
        "key": "acad_pubmed",
        "name": "PubMed生物医学文献",
        "description": "美国国立卫生研究院生物医学和生命科学文献数据库，含摘要、关键词、引用关系。",
        "category": "学术研究",
        "domain_tags": ["医学", "生命科学", "临床", "药物", "公共卫生", "生物"],
        "source_type": "api",
        "icon_color": "#0ea5e9",
        "icon_bg": "#f0f9ff",
        "sample_queries": ["新冠肺炎临床研究文献", "阿尔茨海默病治疗进展", "肿瘤免疫疗法最新研究"],
        "coverage": "1960-至今",
        "doc_count": 36000000,
    },
    {
        "key": "acad_cnki_abstract",
        "name": "中文学术摘要数据",
        "description": "国内重要学术期刊论文摘要和关键词检索，涵盖理工、人文、社科等各学科。",
        "category": "学术研究",
        "domain_tags": ["中文论文", "CNKI", "学术期刊", "核心期刊", "硕博论文"],
        "source_type": "builtin",
        "icon_color": "#b45309",
        "icon_bg": "#fef3c7",
        "sample_queries": ["碳中和政策效果研究综述", "新能源汽车消费影响因素", "数字经济与实体经济融合"],
        "coverage": "2000-至今",
        "doc_count": 80000000,
    },
    {
        "key": "acad_patent_cn",
        "name": "中国专利数据库",
        "description": "国家知识产权局发明专利、实用新型、外观设计专利全文，含申请人、分类号、法律状态。",
        "category": "学术研究",
        "domain_tags": ["专利", "发明", "知识产权", "CNIPA", "技术创新"],
        "source_type": "api",
        "icon_color": "#6366f1",
        "icon_bg": "#eef2ff",
        "sample_queries": ["华为5G技术专利数量", "新能源汽车电池专利分布", "人工智能领域专利申请趋势"],
        "coverage": "1985-至今",
        "doc_count": 18000000,
    },
    {
        "key": "acad_ssrn",
        "name": "社会科学研究网络",
        "description": "SSRN经济学、金融学、法律、管理学工作论文预印本，包含大量政策研究和实证分析。",
        "category": "学术研究",
        "domain_tags": ["SSRN", "经济学", "金融学", "法律", "工作论文"],
        "source_type": "web",
        "icon_color": "#0ea5e9",
        "icon_bg": "#f0f9ff",
        "sample_queries": ["利率与资产价格研究", "中国股市流动性文献", "货币政策传导机制工作论文"],
        "coverage": "1994-至今",
        "doc_count": 1100000,
    },

    # ── 政府与政策 ────────────────────────────────────────────────────────

    {
        "key": "gov_report_cn",
        "name": "政府工作报告",
        "description": "历届全国人民代表大会国务院政府工作报告全文，含年度目标、经济政策、社会发展任务。",
        "category": "政府与政策",
        "domain_tags": ["政府工作报告", "国务院", "全国人大", "政策目标", "五年规划"],
        "source_type": "web",
        "icon_color": "#dc2626",
        "icon_bg": "#fef2f2",
        "sample_queries": ["2024年GDP增长目标", "历年政府工作报告关键词对比", "就业政策历年演变"],
        "coverage": "1954-至今",
        "doc_count": 70,
    },
    {
        "key": "gov_policy_cn",
        "name": "中央政策文件",
        "description": "国务院、国务院办公厅正式发布的国发、国办文件，含行政法规、规范性文件、批复。",
        "category": "政府与政策",
        "domain_tags": ["国务院", "政策文件", "国发文件", "行政法规", "规范性文件"],
        "source_type": "web",
        "icon_color": "#dc2626",
        "icon_bg": "#fef2f2",
        "sample_queries": ["数字经济发展政策", "碳达峰行动方案文件", "国家数据局相关政策"],
        "coverage": "1949-至今",
        "doc_count": 45000,
    },
    {
        "key": "gov_stats_cn",
        "name": "国家统计局数据",
        "description": "国家统计局官方发布的人口、工业、农业、对外贸易、固定资产投资等统计数据。",
        "category": "政府与政策",
        "domain_tags": ["国家统计局", "统计数据", "人口普查", "工业统计", "贸易统计"],
        "source_type": "api",
        "icon_color": "#10b981",
        "icon_bg": "#ecfdf5",
        "sample_queries": ["全国人口数量最新统计", "规模以上工业增加值", "城镇居民可支配收入"],
        "coverage": "1978-至今",
        "doc_count": 500000,
    },
    {
        "key": "gov_customs_cn",
        "name": "中国海关进出口数据",
        "description": "海关总署按月发布的进出口总额、主要商品进出口量值、主要贸易伙伴数据。",
        "category": "政府与政策",
        "domain_tags": ["海关", "进出口", "贸易", "顺差", "逆差", "商品贸易"],
        "source_type": "api",
        "icon_color": "#10b981",
        "icon_bg": "#ecfdf5",
        "sample_queries": ["2024年进出口总额", "对美出口月度数据", "芯片进口金额统计"],
        "coverage": "2000-至今",
        "doc_count": 8000,
    },
    {
        "key": "gov_pboc",
        "name": "人民银行货币金融数据",
        "description": "中国人民银行发布的社会融资规模、M2/M1货币供应量、贷款利率、外汇储备数据。",
        "category": "政府与政策",
        "domain_tags": ["人民银行", "货币政策", "M2", "社融", "LPR", "外汇储备"],
        "source_type": "api",
        "icon_color": "#dc2626",
        "icon_bg": "#fef2f2",
        "sample_queries": ["M2货币供应量最新数据", "社会融资规模存量", "LPR利率历史变动"],
        "coverage": "2000-至今",
        "doc_count": 12000,
    },
    {
        "key": "gov_ndrc",
        "name": "国家发改委政策与规划",
        "description": "国家发展和改革委员会发布的五年规划、行业政策、价格监管、项目审批公告。",
        "category": "政府与政策",
        "domain_tags": ["发改委", "五年规划", "价格政策", "项目审批", "产业规划"],
        "source_type": "web",
        "icon_color": "#dc2626",
        "icon_bg": "#fef2f2",
        "sample_queries": ["十四五规划重点项目", "天然气价格监管政策", "新能源汽车基础设施规划"],
        "coverage": "2000-至今",
        "doc_count": 30000,
    },
    {
        "key": "gov_mof",
        "name": "财政部财政数据",
        "description": "财政部公开的财政收支月报、地方政府债务、预算执行情况及财税政策文件。",
        "category": "政府与政策",
        "domain_tags": ["财政部", "财政收支", "地方债", "税收", "预算", "专项债"],
        "source_type": "api",
        "icon_color": "#10b981",
        "icon_bg": "#ecfdf5",
        "sample_queries": ["全国财政收入月度数据", "地方政府专项债发行规模", "增值税减免政策"],
        "coverage": "2010-至今",
        "doc_count": 6000,
    },
    {
        "key": "gov_local_stats",
        "name": "省市统计年鉴",
        "description": "31省市区及主要城市统计局发布的年度统计年鉴，含地区GDP、人口、产业结构数据。",
        "category": "政府与政策",
        "domain_tags": ["省级统计", "城市数据", "统计年鉴", "地区GDP", "人口分布"],
        "source_type": "builtin",
        "icon_color": "#10b981",
        "icon_bg": "#ecfdf5",
        "sample_queries": ["各省GDP排名2023", "上海市人口规模统计", "广东省工业增加值"],
        "coverage": "2010-至今",
        "doc_count": 3100,
    },

    # ── 企业信息 ──────────────────────────────────────────────────────────

    {
        "key": "corp_registration",
        "name": "工商注册与企业基本信息",
        "description": "企业营业执照信息、注册资本、法定代表人、经营范围、股东结构等工商注册基础信息。",
        "category": "企业信息",
        "domain_tags": ["工商", "营业执照", "企业注册", "法人", "股权结构"],
        "source_type": "api",
        "icon_color": "#6366f1",
        "icon_bg": "#eef2ff",
        "sample_queries": ["字节跳动注册资本查询", "某企业股东穿透信息", "行业内企业注册数量统计"],
        "coverage": "2000-至今",
        "doc_count": 200000000,
    },
    {
        "key": "corp_judicial",
        "name": "司法风险数据",
        "description": "被执行人信息、失信被执行人(老赖)名单、企业涉诉案件、法院判决摘要。",
        "category": "企业信息",
        "domain_tags": ["被执行人", "失信", "诉讼", "司法风险", "法院"],
        "source_type": "api",
        "icon_color": "#f59e0b",
        "icon_bg": "#fffbeb",
        "sample_queries": ["某企业是否被列为失信被执行人", "企业涉诉案件数量", "行业诉讼风险分布"],
        "coverage": "2013-至今",
        "doc_count": 50000000,
    },
    {
        "key": "corp_esg",
        "name": "企业ESG与社会责任报告",
        "description": "A股上市公司ESG评级、社会责任报告全文、碳排放披露数据、治理结构信息。",
        "category": "企业信息",
        "domain_tags": ["ESG", "社会责任", "可持续发展", "碳披露", "公司治理"],
        "source_type": "web",
        "icon_color": "#10b981",
        "icon_bg": "#ecfdf5",
        "sample_queries": ["A股ESG评级分布", "煤炭企业碳排放披露", "企业ESG报告关键指标"],
        "coverage": "2015-至今",
        "doc_count": 8000,
    },
    {
        "key": "corp_tender",
        "name": "政府采购与招投标公告",
        "description": "中国政府采购网及各地公共资源交易中心发布的招标公告、中标结果、采购计划。",
        "category": "企业信息",
        "domain_tags": ["招标", "投标", "政府采购", "中标", "公共资源交易"],
        "source_type": "web",
        "icon_color": "#8b5cf6",
        "icon_bg": "#f5f3ff",
        "sample_queries": ["医院IT设备采购招标", "某企业中标金额统计", "软件开发项目招标公告"],
        "coverage": "2015-至今",
        "doc_count": 10000000,
    },
    {
        "key": "corp_announcement",
        "name": "上市公司公告与披露",
        "description": "沪深交易所上市公司临时公告、定期报告、重大事项披露，含并购重组、定向增发等。",
        "category": "企业信息",
        "domain_tags": ["公告", "披露", "重大事项", "并购", "定增", "上市公司"],
        "source_type": "api",
        "icon_color": "#ef4444",
        "icon_bg": "#fef2f2",
        "sample_queries": ["某公司最新公告", "本周重大并购重组事件", "定向增发公告统计"],
        "coverage": "2000-至今",
        "doc_count": 5000000,
    },

    # ── 新闻与舆情 ────────────────────────────────────────────────────────

    {
        "key": "news_financial",
        "name": "财经新闻",
        "description": "证券时报、上海证券报、第一财经、财新网等权威财经媒体实时资讯与深度报道。",
        "category": "新闻与舆情",
        "domain_tags": ["财经新闻", "证券时报", "第一财经", "财新", "经济日报"],
        "source_type": "rss",
        "icon_color": "#f59e0b",
        "icon_bg": "#fffbeb",
        "sample_queries": ["今日A股市场综述", "最新货币政策解读", "财经热点新闻"],
        "coverage": "2020-至今",
        "doc_count": 3000000,
    },
    {
        "key": "news_tech",
        "name": "科技新闻",
        "description": "科技日报、IT之家、36氪、虎嗅等科技媒体最新资讯，含AI、半导体、互联网行业动态。",
        "category": "新闻与舆情",
        "domain_tags": ["科技新闻", "AI", "半导体", "互联网", "科技日报"],
        "source_type": "rss",
        "icon_color": "#0ea5e9",
        "icon_bg": "#f0f9ff",
        "sample_queries": ["AI大模型最新进展", "芯片行业新闻", "国内科技公司动态"],
        "coverage": "2020-至今",
        "doc_count": 2500000,
    },
    {
        "key": "news_politics",
        "name": "政治时事新闻",
        "description": "新华社、人民日报、央视新闻国内政治、党政动态、重大政策发布及官方权威报道。",
        "category": "新闻与舆情",
        "domain_tags": ["新华社", "人民日报", "央视", "时政", "党政"],
        "source_type": "rss",
        "icon_color": "#dc2626",
        "icon_bg": "#fef2f2",
        "sample_queries": ["中央最新政策动向", "高层领导人活动新闻", "重要会议精神传达"],
        "coverage": "2020-至今",
        "doc_count": 5000000,
    },
    {
        "key": "news_international",
        "name": "国际新闻",
        "description": "路透社、彭博社、BBC、法新社国际新闻摘要，含地缘政治、全球经济、外交动态。",
        "category": "新闻与舆情",
        "domain_tags": ["国际新闻", "路透", "彭博", "BBC", "外交", "地缘政治"],
        "source_type": "rss",
        "icon_color": "#6366f1",
        "icon_bg": "#eef2ff",
        "sample_queries": ["中美贸易摩擦最新动态", "俄乌冲突进展", "全球央行政策动向"],
        "coverage": "2020-至今",
        "doc_count": 8000000,
    },
    {
        "key": "news_sports",
        "name": "体育新闻",
        "description": "国内外主要体育赛事动态，包含足球、篮球、网球、奥运、亚运等赛事成绩与转会新闻。",
        "category": "新闻与舆情",
        "domain_tags": ["体育新闻", "足球", "篮球", "奥运", "赛事", "转会"],
        "source_type": "rss",
        "icon_color": "#10b981",
        "icon_bg": "#ecfdf5",
        "sample_queries": ["中国女足最新赛况", "NBA今日比赛结果", "世界杯预选赛赛程"],
        "coverage": "2020-至今",
        "doc_count": 1500000,
    },
    {
        "key": "news_entertainment",
        "name": "文娱新闻",
        "description": "国内外票房榜、影视剧播放量、音乐榜单、明星动态及文化产业政策资讯。",
        "category": "新闻与舆情",
        "domain_tags": ["娱乐新闻", "票房", "影视", "音乐", "文化产业"],
        "source_type": "rss",
        "icon_color": "#ec4899",
        "icon_bg": "#fdf2f8",
        "sample_queries": ["2024年春节档票房排名", "最新爆款剧集收视率", "音乐流媒体排行榜"],
        "coverage": "2020-至今",
        "doc_count": 1200000,
    },
    {
        "key": "news_social",
        "name": "社会民生新闻",
        "description": "社会热点、民生政策、城市治理、教育医疗住房等社会议题深度报道。",
        "category": "新闻与舆情",
        "domain_tags": ["社会新闻", "民生", "城市治理", "教育", "医疗", "住房"],
        "source_type": "rss",
        "icon_color": "#14b8a6",
        "icon_bg": "#f0fdfa",
        "sample_queries": ["医疗改革最新政策", "城市老龄化问题报道", "教育减负政策落实"],
        "coverage": "2020-至今",
        "doc_count": 2000000,
    },

    # ── 行业数据 ──────────────────────────────────────────────────────────

    {
        "key": "industry_auto",
        "name": "汽车行业数据",
        "description": "中国汽车工业协会月度产销数据，包含新能源汽车分车型销量、品牌市占率、出口情况。",
        "category": "行业数据",
        "domain_tags": ["汽车", "新能源汽车", "销量", "产量", "电动车", "中汽协"],
        "source_type": "api",
        "icon_color": "#6366f1",
        "icon_bg": "#eef2ff",
        "sample_queries": ["新能源汽车月度销量", "比亚迪市场占有率", "汽车出口数量统计"],
        "coverage": "2015-至今",
        "doc_count": 5000,
    },
    {
        "key": "industry_realestate",
        "name": "房地产数据",
        "description": "70城房价指数、全国商品房销售面积、土地成交价格、库存去化周期等房地产核心指标。",
        "category": "行业数据",
        "domain_tags": ["房地产", "房价", "土地", "商品房", "房屋销售", "库存"],
        "source_type": "api",
        "icon_color": "#f59e0b",
        "icon_bg": "#fffbeb",
        "sample_queries": ["北京新房价格指数", "全国商品房销售面积月度数据", "土地成交溢价率统计"],
        "coverage": "2010-至今",
        "doc_count": 15000,
    },
    {
        "key": "industry_energy",
        "name": "能源数据",
        "description": "全国电力供需情况、煤炭产销数据、天然气产量消费、国际油价及国内成品油价格。",
        "category": "行业数据",
        "domain_tags": ["能源", "电力", "煤炭", "天然气", "油价", "可再生能源"],
        "source_type": "api",
        "icon_color": "#f59e0b",
        "icon_bg": "#fffbeb",
        "sample_queries": ["全国发电量月度数据", "煤炭库存变化", "国内成品油价格调整历史"],
        "coverage": "2010-至今",
        "doc_count": 8000,
    },
    {
        "key": "industry_agri",
        "name": "农业与粮食数据",
        "description": "粮食总产量、播种面积、农产品市场价格、农业生产资料价格、农村人均收入。",
        "category": "行业数据",
        "domain_tags": ["农业", "粮食", "农产品", "种植", "化肥", "农药"],
        "source_type": "api",
        "icon_color": "#84cc16",
        "icon_bg": "#f7fee7",
        "sample_queries": ["小麦产量历年统计", "猪肉市场价格走势", "农产品批发价格指数"],
        "coverage": "2000-至今",
        "doc_count": 10000,
    },
    {
        "key": "industry_pharma",
        "name": "医药与医疗数据",
        "description": "国家药监局新药审批、医院诊疗量统计、医药行业产值、集中采购中标价格数据。",
        "category": "行业数据",
        "domain_tags": ["医药", "药品审批", "医疗器械", "集采", "医院", "NMPA"],
        "source_type": "api",
        "icon_color": "#0ea5e9",
        "icon_bg": "#f0f9ff",
        "sample_queries": ["年度新药批准数量", "集采中标药品清单", "医疗行业产值增速"],
        "coverage": "2015-至今",
        "doc_count": 20000,
    },
    {
        "key": "industry_retail",
        "name": "零售与消费数据",
        "description": "社会消费品零售总额月度数据、电商GMV、实物商品网络零售额、消费者信心指数。",
        "category": "行业数据",
        "domain_tags": ["零售", "消费", "电商", "GMV", "社零", "消费升级"],
        "source_type": "api",
        "icon_color": "#ec4899",
        "icon_bg": "#fdf2f8",
        "sample_queries": ["社会消费品零售总额月度数据", "双十一全网销售额历年对比", "线上零售占比趋势"],
        "coverage": "2015-至今",
        "doc_count": 6000,
    },
    {
        "key": "industry_logistics",
        "name": "物流与运输数据",
        "description": "快递业务量月度统计、全国铁路货运量、港口集装箱吞吐量、航运运费指数。",
        "category": "行业数据",
        "domain_tags": ["物流", "快递", "航运", "铁路货运", "港口", "运费指数"],
        "source_type": "api",
        "icon_color": "#f59e0b",
        "icon_bg": "#fffbeb",
        "sample_queries": ["快递业务量月度统计", "上海港集装箱吞吐量", "BDI波罗的海干散货运价指数"],
        "coverage": "2015-至今",
        "doc_count": 5000,
    },
    {
        "key": "industry_telecom",
        "name": "通信与互联网数据",
        "description": "工信部电信业统计、5G用户数、宽带接入用户、移动互联网流量、互联网经济规模。",
        "category": "行业数据",
        "domain_tags": ["电信", "5G", "宽带", "互联网", "移动用户", "工信部"],
        "source_type": "api",
        "icon_color": "#0ea5e9",
        "icon_bg": "#f0f9ff",
        "sample_queries": ["5G用户累计数量", "移动互联网流量月度统计", "三大运营商营收对比"],
        "coverage": "2015-至今",
        "doc_count": 4000,
    },

    # ── 气象与环境 ────────────────────────────────────────────────────────

    {
        "key": "env_weather_cn",
        "name": "中国天气预报数据",
        "description": "中国气象局7日天气预报、历史气候数据，涵盖温度、降水、风力、能见度等要素。",
        "category": "气象与环境",
        "domain_tags": ["天气", "气象", "预报", "降雨", "温度", "气候"],
        "source_type": "api",
        "icon_color": "#0ea5e9",
        "icon_bg": "#f0f9ff",
        "sample_queries": ["北京未来7天天气预报", "上海月均气温历史数据", "全国极端天气事件统计"],
        "coverage": "2010-至今",
        "doc_count": 100000,
    },
    {
        "key": "env_climate",
        "name": "气候变化数据",
        "description": "全球平均气温变化、海平面上升速率、极端天气事件频率等气候变化核心指标。",
        "category": "气象与环境",
        "domain_tags": ["气候变化", "全球变暖", "温室气体", "极端天气", "IPCC"],
        "source_type": "api",
        "icon_color": "#f59e0b",
        "icon_bg": "#fffbeb",
        "sample_queries": ["全球年均气温变化趋势", "中国近50年气候变化", "极端降水事件频率统计"],
        "coverage": "1950-至今",
        "doc_count": 50000,
    },
    {
        "key": "env_pollution",
        "name": "环境质量数据",
        "description": "全国338城市AQI空气质量指数、PM2.5浓度、主要河流水质监测、土壤污染状况。",
        "category": "气象与环境",
        "domain_tags": ["AQI", "空气质量", "PM2.5", "水质", "土壤", "环境污染"],
        "source_type": "api",
        "icon_color": "#10b981",
        "icon_bg": "#ecfdf5",
        "sample_queries": ["北京今日AQI指数", "长三角空气质量对比", "主要江河水质监测数据"],
        "coverage": "2013-至今",
        "doc_count": 200000,
    },
    {
        "key": "env_carbon",
        "name": "碳排放与双碳政策数据",
        "description": "全国碳市场碳排放配额价格、行业碳排放数据、双碳政策文件、CCER核证减排量。",
        "category": "气象与环境",
        "domain_tags": ["碳排放", "碳市场", "双碳", "CCER", "碳配额", "碳交易"],
        "source_type": "api",
        "icon_color": "#84cc16",
        "icon_bg": "#f7fee7",
        "sample_queries": ["全国碳市场配额价格", "各行业碳排放强度对比", "碳达峰碳中和政策清单"],
        "coverage": "2021-至今",
        "doc_count": 10000,
    },
    {
        "key": "env_disaster",
        "name": "自然灾害预警与历史数据",
        "description": "地震、洪涝、干旱、台风等自然灾害预警信息及历年灾害损失统计数据。",
        "category": "气象与环境",
        "domain_tags": ["自然灾害", "地震", "洪涝", "台风", "干旱", "灾害预警"],
        "source_type": "api",
        "icon_color": "#ef4444",
        "icon_bg": "#fef2f2",
        "sample_queries": ["近期地震震情统计", "历年台风登陆中国情况", "洪涝灾害损失历史数据"],
        "coverage": "2000-至今",
        "doc_count": 30000,
    },

    # ── 法律法规 ──────────────────────────────────────────────────────────

    {
        "key": "law_statute_cn",
        "name": "中国现行法律法规全文",
        "description": "全国人民代表大会、国务院颁布的现行有效法律、行政法规全文，含最新修订版本。",
        "category": "法律法规",
        "domain_tags": ["法律", "法规", "全国人大", "行政法规", "立法"],
        "source_type": "web",
        "icon_color": "#8b5cf6",
        "icon_bg": "#f5f3ff",
        "sample_queries": ["公司法最新修订全文", "数据安全法条文解读", "劳动合同法具体条款"],
        "coverage": "1949-至今",
        "doc_count": 10000,
    },
    {
        "key": "law_judicial_cn",
        "name": "司法裁判文书",
        "description": "中国裁判文书网公开的法院判决书、裁定书，含当事人信息、案由、裁判结果。",
        "category": "法律法规",
        "domain_tags": ["裁判文书", "判决", "裁定", "诉讼", "中国裁判文书网"],
        "source_type": "web",
        "icon_color": "#8b5cf6",
        "icon_bg": "#f5f3ff",
        "sample_queries": ["劳动争议典型判决案例", "知识产权侵权案裁判标准", "合同纠纷相关判决"],
        "coverage": "2014-至今",
        "doc_count": 130000000,
    },
    {
        "key": "law_regulation_cn",
        "name": "部委规章与地方性法规",
        "description": "国务院各部委行政规章、31省市地方性法规及政府规章，含最新修订文本。",
        "category": "法律法规",
        "domain_tags": ["部委规章", "地方法规", "地方政府规章", "行政规范"],
        "source_type": "web",
        "icon_color": "#8b5cf6",
        "icon_bg": "#f5f3ff",
        "sample_queries": ["银行监管规章最新版", "上海市地方性法规查询", "证券监管规章全文"],
        "coverage": "2000-至今",
        "doc_count": 200000,
    },
    {
        "key": "law_compliance",
        "name": "合规与监管政策",
        "description": "金融、互联网、医药等重点行业监管规定、合规指引、处罚案例汇编。",
        "category": "法律法规",
        "domain_tags": ["合规", "监管", "金融监管", "数据合规", "反垄断"],
        "source_type": "web",
        "icon_color": "#8b5cf6",
        "icon_bg": "#f5f3ff",
        "sample_queries": ["互联网平台反垄断监管案例", "数据跨境传输合规要求", "金融机构反洗钱规定"],
        "coverage": "2015-至今",
        "doc_count": 50000,
    },

    # ── 国际与全球 ────────────────────────────────────────────────────────

    {
        "key": "intl_worldbank",
        "name": "世界银行发展数据",
        "description": "世界银行WDI数据库，含190+国家GDP、贫困率、教育、卫生、基础设施等发展指标。",
        "category": "国际与全球",
        "domain_tags": ["世界银行", "WDI", "发展指标", "国际比较", "全球经济"],
        "source_type": "api",
        "icon_color": "#0ea5e9",
        "icon_bg": "#f0f9ff",
        "sample_queries": ["中国GDP增长率历史数据", "全球贫困人口变化趋势", "各国人均GNI对比"],
        "coverage": "1960-至今",
        "doc_count": 2000,
    },
    {
        "key": "intl_imf",
        "name": "IMF世界经济展望数据",
        "description": "国际货币基金组织WEO数据库，全球及各国GDP预测、通货膨胀、经常账户余额等。",
        "category": "国际与全球",
        "domain_tags": ["IMF", "WEO", "全球经济", "通货膨胀", "经济预测"],
        "source_type": "api",
        "icon_color": "#0ea5e9",
        "icon_bg": "#f0f9ff",
        "sample_queries": ["IMF对中国GDP预测", "全球通胀率展望", "新兴市场经济增速对比"],
        "coverage": "1980-至今",
        "doc_count": 1000,
    },
    {
        "key": "intl_un_stats",
        "name": "联合国统计数据库",
        "description": "联合国统计司全球可持续发展目标(SDG)进展、人口统计、贸易统计等多维度数据集。",
        "category": "国际与全球",
        "domain_tags": ["联合国", "SDG", "可持续发展", "全球统计", "人口"],
        "source_type": "api",
        "icon_color": "#6366f1",
        "icon_bg": "#eef2ff",
        "sample_queries": ["SDG目标完成进度", "全球人口预测数据", "联合国发展指数排名"],
        "coverage": "2000-至今",
        "doc_count": 5000,
    },
    {
        "key": "intl_trade",
        "name": "全球贸易数据",
        "description": "WTO贸易统计、UN Comtrade双边贸易数据，按商品类别、国家对的进出口详细数据。",
        "category": "国际与全球",
        "domain_tags": ["WTO", "Comtrade", "全球贸易", "双边贸易", "出口", "进口"],
        "source_type": "api",
        "icon_color": "#10b981",
        "icon_bg": "#ecfdf5",
        "sample_queries": ["中美商品贸易额统计", "全球芯片进出口数据", "WTO贸易增速预测"],
        "coverage": "2000-至今",
        "doc_count": 10000,
    },
    {
        "key": "intl_geopolitics",
        "name": "地缘政治与国际关系报告",
        "description": "兰德公司、布鲁金斯学会、SIPRI等国际智库地缘政治分析报告、军费数据、冲突数据库。",
        "category": "国际与全球",
        "domain_tags": ["地缘政治", "国际关系", "智库报告", "军费", "冲突"],
        "source_type": "web",
        "icon_color": "#6366f1",
        "icon_bg": "#eef2ff",
        "sample_queries": ["全球军费开支排名", "地缘冲突对能源价格影响", "SIPRI武器贸易数据"],
        "coverage": "2015-至今",
        "doc_count": 50000,
    },

    # ── 医疗健康 ──────────────────────────────────────────────────────────

    {
        "key": "health_disease",
        "name": "疾病数据与流行病学",
        "description": "WHO全球疾病负担、传染病报告、慢性病流行率、中国疾病预防控制中心公开数据。",
        "category": "医疗健康",
        "domain_tags": ["疾病", "流行病学", "WHO", "传染病", "慢性病", "疾控"],
        "source_type": "api",
        "icon_color": "#0ea5e9",
        "icon_bg": "#f0f9ff",
        "sample_queries": ["全球糖尿病患者人数", "中国传染病年度报告", "心血管疾病死亡率统计"],
        "coverage": "2000-至今",
        "doc_count": 100000,
    },
    {
        "key": "health_drug",
        "name": "药品说明与临床数据",
        "description": "国家药监局已批准药品说明书数据库、临床试验注册信息、不良反应监测报告。",
        "category": "医疗健康",
        "domain_tags": ["药品说明书", "临床试验", "不良反应", "药监局", "仿制药"],
        "source_type": "api",
        "icon_color": "#0ea5e9",
        "icon_bg": "#f0f9ff",
        "sample_queries": ["某药品说明书全文", "在研临床试验注册查询", "药品不良反应监测报告"],
        "coverage": "2015-至今",
        "doc_count": 300000,
    },
    {
        "key": "health_policy",
        "name": "医疗卫生政策",
        "description": "国家卫生健康委员会医疗改革政策、DRG/DIP支付改革、公立医院绩效考核、医保政策文件。",
        "category": "医疗健康",
        "domain_tags": ["医改", "医疗政策", "医保", "DRG", "公立医院", "卫健委"],
        "source_type": "web",
        "icon_color": "#10b981",
        "icon_bg": "#ecfdf5",
        "sample_queries": ["DRG支付改革最新进展", "医保目录调整政策", "公立医院改革政策文件"],
        "coverage": "2015-至今",
        "doc_count": 5000,
    },

    # ── 教育 ──────────────────────────────────────────────────────────────

    {
        "key": "edu_stats_cn",
        "name": "教育统计数据",
        "description": "教育部历年教育统计公报，含各级学校招生规模、毕业生就业率、院校数量等关键指标。",
        "category": "教育",
        "domain_tags": ["教育统计", "高校招生", "毕业生", "就业率", "教育部"],
        "source_type": "api",
        "icon_color": "#8b5cf6",
        "icon_bg": "#f5f3ff",
        "sample_queries": ["高校毕业生规模历年统计", "本科招生人数变化", "职业教育发展数据"],
        "coverage": "2010-至今",
        "doc_count": 15000,
    },
    {
        "key": "edu_policy",
        "name": "教育政策与高考数据",
        "description": "教育部高考改革政策、双减政策文件、高考分数线历年汇总、教育经费投入统计。",
        "category": "教育",
        "domain_tags": ["教育政策", "高考", "双减", "分数线", "教育改革"],
        "source_type": "web",
        "icon_color": "#8b5cf6",
        "icon_bg": "#f5f3ff",
        "sample_queries": ["历年高考分数线汇总", "双减政策执行情况报告", "教育经费占GDP比例"],
        "coverage": "2010-至今",
        "doc_count": 5000,
    },
]


async def init_official_sources(db: AsyncSession) -> None:
    """Seed the official_datasources table from the static list.

    Only inserts records that do not yet exist (by key).  Safe to call on
    every startup — idempotent, never overwrites user-modified rows.
    """
    from app.models.official_datasource import OfficialDataSource

    try:
        existing = (await db.execute(select(OfficialDataSource.key))).scalars().all()
        existing_keys = set(existing)

        new_rows = 0
        for src in OFFICIAL_SOURCES:
            if src["key"] in existing_keys:
                continue
            row = OfficialDataSource(
                key=src["key"],
                name=src["name"],
                description=src.get("description", ""),
                category=src["category"],
                domain_tags=json.dumps(src.get("domain_tags", []), ensure_ascii=False),
                is_active=src.get("is_active", True),
                source_type=src.get("source_type", "builtin"),
                icon_color=src.get("icon_color", "#6366f1"),
                icon_bg=src.get("icon_bg", "#eef2ff"),
                api_config=json.dumps(src.get("api_config", {}), ensure_ascii=False),
                sample_queries=json.dumps(src.get("sample_queries", []), ensure_ascii=False),
                coverage=src.get("coverage", "2020-至今"),
                doc_count=src.get("doc_count", 0),
            )
            db.add(row)
            new_rows += 1

        if new_rows:
            await db.commit()
            logger.info("[datasource_registry] Seeded %d official sources", new_rows)
    except Exception as exc:
        logger.warning("[datasource_registry] Seed failed (non-fatal): %s", exc)
        await db.rollback()
